### ISSUE TITLE
Please consider renaming this to something less generic

### ISSUE THREAD

**Issue by unixorn** [ncihnegn/zsh-theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by ncihnegn** [comment]
Can you refer to it as ncihnegn/zsh-theme?

**Comment by unixorn** [comment]
Could you name it ncihnegn/ncihnegn? zsh-theme is too generic and I prefer to not include account names in the link titles.

**Comment by ncihnegn** [comment]
I hope you understand I won't use my account name for a theme repo.
How about "[ncihnegn](https://github.com/ncihnegn/zsh-theme)"?

**Comment by unixorn** [comment]
How about ncihnegn-zsh-theme? My goal is to make it clear in people's `.zshrc` or ZSH framework configuration - keeping the repo named after the theme makes it easier to figure things out when they go back to update their configuration months later.

**Comment by ncihnegn** [comment]
I understand. But I don't think it is a problem.
Check the README; you have to refer to my user name to use this.

**Comment by unixorn** [comment]
Ok, I won't add it.
